# Generated by Django 4.2.23 on 2025-07-30 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('lessons', '0001_initial'),
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_answer', models.JSONField()),
                ('is_correct', models.BooleanField(default=False)),
                ('points_earned', models.IntegerField(default=0)),
                ('time_spent_seconds', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('true_false', 'True/False'), ('fill_blank', 'Fill in the Blank'), ('matching', 'Matching'), ('audio', 'Audio')], max_length=20)),
                ('question_text', models.TextField()),
                ('options', models.JSONField(blank=True, default=list)),
                ('correct_answer', models.JSONField()),
                ('explanation', models.TextField(blank=True)),
                ('points', models.IntegerField(default=10)),
                ('order', models.PositiveIntegerField()),
                ('audio_url', models.URLField(blank=True, null=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.RemoveField(
            model_name='questionanswer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='questionanswer',
            name='quiz_attempt',
        ),
        migrations.AlterUniqueTogether(
            name='questionchoice',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='questionchoice',
            name='question',
        ),
        migrations.AlterModelOptions(
            name='quizattempt',
            options={'ordering': ['-started_at']},
        ),
        migrations.RemoveField(
            model_name='quizattempt',
            name='correct_answers',
        ),
        migrations.RemoveField(
            model_name='quizattempt',
            name='time_taken_minutes',
        ),
        migrations.RemoveField(
            model_name='quizattempt',
            name='total_questions',
        ),
        migrations.AddField(
            model_name='quiz',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='courses.course'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='max_attempts',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='quiz',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='xp_reward',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='earned_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='started_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='time_spent_seconds',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='total_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='lessons.lesson'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='time_limit_minutes',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='passed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='score',
            field=models.FloatField(default=0.0),
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='QuestionAnswer',
        ),
        migrations.DeleteModel(
            name='QuestionChoice',
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quizzes.quiz'),
        ),
        migrations.AddField(
            model_name='quizanswer',
            name='attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quizzes.quizattempt'),
        ),
        migrations.AddField(
            model_name='quizanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.quizquestion'),
        ),
        migrations.AlterUniqueTogether(
            name='quizquestion',
            unique_together={('quiz', 'order')},
        ),
    ]
