# Generated by Django 4.2.23 on 2025-08-07 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprogress',
            name='lessons_completed',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='quizzes_completed',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='total_study_time',
            field=models.IntegerField(default=30),
        ),
    ]
