# Generated by Django 4.2.23 on 2025-08-07 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0002_alter_userprogress_lessons_completed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyactivity',
            name='lessons_completed',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='dailyactivity',
            name='study_time_minutes',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='dailyactivity',
            name='xp_earned',
            field=models.IntegerField(default=45),
        ),
    ]
