# Generated by Django 4.2.23 on 2025-07-28 14:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lessons', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FlashCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=200)),
                ('translation', models.CharField(max_length=200)),
                ('pronunciation', models.CharField(blank=True, max_length=200)),
                ('audio_pronunciation', models.FileField(blank=True, null=True, upload_to='pronunciations/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='flashcard_images/')),
                ('example_sentence', models.TextField(blank=True)),
                ('example_translation', models.TextField(blank=True)),
                ('difficulty_level', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcards', to='lessons.lesson')),
            ],
        ),
        migrations.CreateModel(
            name='FlashCardReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 'Again'), (2, 'Hard'), (3, 'Good'), (4, 'Easy')])),
                ('interval_days', models.IntegerField(default=1)),
                ('ease_factor', models.FloatField(default=2.5)),
                ('next_review_date', models.DateTimeField()),
                ('reviewed_at', models.DateTimeField(auto_now_add=True)),
                ('flashcard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flashcards.flashcard')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'flashcard')},
            },
        ),
    ]
