# Generated by Django 4.2.23 on 2025-08-02 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessoncompletion',
            name='estimated_duration',
            field=models.IntegerField(default=15),
        ),
        migrations.AddField(
            model_name='lessoncompletion',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
