# Generated by Django 4.2.23 on 2025-08-02 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_lessoncompletion_estimated_duration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessoncompletion',
            name='estimated_duration',
        ),
        migrations.RemoveField(
            model_name='lessoncompletion',
            name='is_active',
        ),
        migrations.AddField(
            model_name='lesson',
            name='estimated_duration',
            field=models.IntegerField(default=15),
        ),
        migrations.AddField(
            model_name='lesson',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
