# Generated by Django 4.2.23 on 2025-08-02 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_options_alter_courseenrollment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='order',
            field=models.IntegerField(default=1),
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['user'], name='courses_cer_user_id_2490e7_idx'),
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['certificate_id'], name='courses_cer_certifi_a9a7a7_idx'),
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['issued_at'], name='courses_cer_issued__20c35d_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['course_level', 'order'], name='courses_cou_course__8bb74b_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['is_active'], name='courses_cou_is_acti_3c7e41_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['is_premium'], name='courses_cou_is_prem_85fcb9_idx'),
        ),
        migrations.AddIndex(
            model_name='courseenrollment',
            index=models.Index(fields=['user', 'course'], name='courses_cou_user_id_147840_idx'),
        ),
        migrations.AddIndex(
            model_name='courseenrollment',
            index=models.Index(fields=['completed_at'], name='courses_cou_complet_17774b_idx'),
        ),
        migrations.AddIndex(
            model_name='courseenrollment',
            index=models.Index(fields=['enrolled_at'], name='courses_cou_enrolle_89b743_idx'),
        ),
        migrations.AddIndex(
            model_name='courselevel',
            index=models.Index(fields=['language', 'order'], name='courses_cou_languag_554bb6_idx'),
        ),
        migrations.AddIndex(
            model_name='courselevel',
            index=models.Index(fields=['difficulty'], name='courses_cou_difficu_d4535a_idx'),
        ),
        migrations.AddIndex(
            model_name='courselevel',
            index=models.Index(fields=['is_active'], name='courses_cou_is_acti_d72e68_idx'),
        ),
        migrations.AddIndex(
            model_name='courserating',
            index=models.Index(fields=['course', 'is_active'], name='courses_cou_course__3ab4c5_idx'),
        ),
        migrations.AddIndex(
            model_name='courserating',
            index=models.Index(fields=['rating'], name='courses_cou_rating_e73fda_idx'),
        ),
        migrations.AddIndex(
            model_name='courserating',
            index=models.Index(fields=['created_at'], name='courses_cou_created_a0bac4_idx'),
        ),
        migrations.AddIndex(
            model_name='language',
            index=models.Index(fields=['code'], name='courses_lan_code_ac7d8b_idx'),
        ),
        migrations.AddIndex(
            model_name='language',
            index=models.Index(fields=['is_active'], name='courses_lan_is_acti_b64152_idx'),
        ),
        migrations.AddIndex(
            model_name='levelenrollment',
            index=models.Index(fields=['user', 'course_level'], name='courses_lev_user_id_e57b30_idx'),
        ),
        migrations.AddIndex(
            model_name='levelenrollment',
            index=models.Index(fields=['completed_at'], name='courses_lev_complet_2c75d9_idx'),
        ),
    ]
