# Generated by Django 4.2.23 on 2025-08-02 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_course_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='flag_image',
            field=models.ImageField(blank=True, null=True, upload_to='flags/'),
        ),
    ]
