# Generated by Django 4.2.23 on 2025-08-02 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_language_flag_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='courselevel',
            name='estimated_duration',
            field=models.PositiveIntegerField(default=1, help_text='Estimated hours to complete'),
        ),
    ]
