# Generated by Django 4.2.23 on 2025-08-06 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_courselevel_estimated_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseenrollment',
            name='last_accessed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='courseenrollment',
            index=models.Index(fields=['last_accessed'], name='courses_cou_last_ac_16cf56_idx'),
        ),
    ]
