# Generated by Django 4.2.23 on 2025-08-06 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_courseenrollment_last_accessed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='xp_reward',
            field=models.IntegerField(default=100, help_text='XP points awarded upon completion'),
        ),
    ]
